feat!: Update lambda module to 3.1.0 to support AWS provider version 4.8+
terraform-aws-modules/terraform-aws-notify-slack pull request #166
Opened 2022-03-30 13:06 UTC by mattoddie

## Description

Due to the breaking changes in AWS provider 4.x, the lambda module used as part of this module has been updated to 3.x to support the new provider. To allow this module to be used with the new provider, we need to update the lambda module version.

## Motivation and Context

This updates the dependent lambda module to version 3.x, allowing this module to be used with AWS provider 4.x.

## Breaking Changes

This is a breaking change as it is no longer compatible with AWS provider 3.x.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have executed `pre-commit run -a` on my pull request

2022-03-30 14:04 UTC, antonbabenko requested changes
Looks pretty good. Could you please apply these fixes and update the docs?

2022-03-30 14:04 UTC, antonbabenko commented on main.tf
> +  version = "~> 3.1"
```suggestion
  version = "3.1.0"
```
It is better to be precise in this module.

2022-03-30 14:04 UTC, antonbabenko commented on examples/notify-slack-simple/versions.tf
> +      version = ">= 4.0.0"
```suggestion
      version = ">= 4.8"
```
4.8 or newer is required by Lambda module. https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v3.1.0/versions.tf#L7

2022-03-30 14:04 UTC, antonbabenko commented on versions.tf
> +      version = ">= 4.0.0"
```suggestion
      version = ">= 4.8"
```

2022-03-30 14:04 UTC, antonbabenko commented on examples/cloudwatch-alerts-to-slack/versions.tf
> +      version = ">= 4.0.0"
```suggestion
      version = ">= 4.8"
```

2022-03-31 11:52 UTC, mattoddie commented
@antonbabenko fixes applied and docs updated

2022-03-31 12:25 UTC, merged

2022-03-31 12:25 UTC, antonbabenko commented
Thanks @mattoddie !

2022-03-31 12:26 UTC, antonbabenko commented
This PR is included in version 5.0.0 :tada: