feat: Improved AWS backup notification readability
terraform-aws-modules/terraform-aws-notify-slack pull request #222
Opened 2024-04-03 06:15 UTC by falense

## Description

When using this module with AWS backup events the resulting message is poorly formatted due to the unstructured nature of the message sent by AWS backup. This PR does a best effort parsing of the message in order to improve readability for the user.

## Motivation and Context

Before
![Screenshot from 2024-04-03 08-08-24](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/assets/2277465/be5f5590-5be5-464e-8ef7-c4a4f9a5e219)

After
![Screenshot from 2024-04-03 08-07-47](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/assets/2277465/6c39f34b-c4b9-4078-b639-ed1973fe77ac)

## Breaking Changes

This should not cause any breaking changes and only affects AWS backup messages

## How Has This Been Tested?

We have been running on our test environment for a couple of weeks now.

2024-04-03 09:10 UTC, antonbabenko requested changes
Looks good. Could you please update tests like described [here](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/tree/master/functions#supporting-additional-events) also?

2024-04-05 10:07 UTC, falense commented
I have added a test according to the examples. Did I do it right? I had some troubles with the somewhat older Python3.8 version so I bumped it to 3.10 to be able to generate the snapshot.

2024-04-16 06:54 UTC, falense commented
I saw that there were more tests. I have corrected the style errors listed below. Is there anything else I can do to get this merged? 

> ./notify_slack.py:290:35: E711 comparison to None should be 'if cond is None:'
./notify_slack.py:298:38: E711 comparison to None should be 'if cond is None:'
./notify_slack.py:307:52: E203 whitespace before ':'

2024-04-23 13:06 UTC, bryantbiggs commented
you'll need to get the CI checks to pass - unfortunately, you have disabled our ability to update your branch so you will have to do these updates on your end

2024-04-24 07:21 UTC, falense commented
I have added you both as maintainers on the fork. Maybe that will do the trick?

2024-04-24 07:47 UTC, antonbabenko commented
Maybe, I will take a look in a few hours today.

2024-04-24 08:03 UTC, falense commented
Brainstormed this with some colleagues. Black suggests adding ignoring  E203 and E701 as a minimal config. See https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#minimal-configuration. I have added the change to the PR.

2024-04-24 10:36 UTC, antonbabenko commented on functions/notify_slack.py
> +    fields:list[Dict[str, Any]] = []
```suggestion
    fields: list[Dict[str, Any]] = []
```

2024-04-24 10:38 UTC, antonbabenko commented
I looked at it, but you still need to fix the failing unit tests and formatting to make GitHub Actions green.

2024-04-24 12:11 UTC, bryantbiggs approved these changes
Added in all of the notification examples from here https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-notifications.html to capture in the snapshots. Not sure why the snapshottest library decided to reformat everything - thats rather unfortunate and noisy but all looks good!

cc @antonbabenko

2024-04-24 12:12 UTC, antonbabenko approved these changes

2024-04-24 12:13 UTC, merged